import type { CourseConfig } from './types'

export const courses: CourseConfig[] = [
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing Certification',
    shortTitle: 'Digital Marketing',
    description: 'Master SEO, social media marketing, PPC, content strategy, and email marketing to grow any business online.',
    icon: 'TrendingUp',
    gradient: 'from-orange-500 to-pink-500',
    accentColor: '#f97316',
    bgGradient: 'linear-gradient(135deg, #f97316 0%, #ec4899 50%, #f43f5e 100%)',
    videos: [
      { title: 'Digital Marketing In 8 Minutes — Simplilearn', youtubeId: '4FX1OLbtFfg', duration: '7:43' },
      { title: 'Digital Marketing Basics & Trends 2025', youtubeId: '-cejOjf1hfs', duration: '5:32' },
    ],
    quizQuestions: [
      { q: 'What does SEO stand for?', options: ['Search Engine Optimization', 'Social Email Outreach', 'Site Enhancement Operations', 'Search Email Optimization'], correct: 0, explanation: 'SEO stands for Search Engine Optimization — the process of improving website visibility in organic search results.' },
      { q: 'Which metric measures the percentage of visitors who leave after viewing one page?', options: ['Click-Through Rate', 'Bounce Rate', 'Conversion Rate', 'Engagement Rate'], correct: 1, explanation: 'Bounce Rate shows the percentage of single-page sessions where users left without interaction.' },
      { q: 'What is PPC advertising?', options: ['Pay Per Click — you pay each time someone clicks your ad', 'Post Per Channel — publishing content across platforms', 'Price Per Conversion — cost of each sale', 'Paid Page Content — sponsored articles'], correct: 0, explanation: 'PPC (Pay Per Click) is an advertising model where you pay a fee each time your ad is clicked.' },
      { q: 'Which social media platform is best for B2B marketing?', options: ['TikTok', 'Snapchat', 'LinkedIn', 'Pinterest'], correct: 2, explanation: 'LinkedIn is the leading platform for B2B marketing, professional networking, and lead generation.' },
      { q: 'What is A/B testing in marketing?', options: ['Testing two cities for product launch', 'Comparing two versions of content to see which performs better', 'A grading system for ads', 'Testing morning vs evening ad schedules'], correct: 1, explanation: 'A/B testing compares two versions (A and B) of a webpage, email, or ad to determine which performs better.' },
      { q: 'What does ROI stand for?', options: ['Rate of Interest', 'Return on Investment', 'Revenue on Impression', 'Reach of Influence'], correct: 1, explanation: 'ROI (Return on Investment) measures the profitability of an investment relative to its cost.' },
      { q: 'Which of these is NOT a type of digital marketing?', options: ['Content Marketing', 'Billboard Marketing', 'Email Marketing', 'Influencer Marketing'], correct: 1, explanation: 'Billboard marketing is a form of traditional advertising, not digital marketing.' },
      { q: 'What is a "conversion" in digital marketing?', options: ['Changing website design', 'A desired action taken by a user (purchase, sign-up)', 'Switching ad platforms', 'Converting images to video'], correct: 1, explanation: 'A conversion is when a user completes a desired action, such as making a purchase or signing up.' },
      { q: 'What is Google Analytics used for?', options: ['Creating Google Ads', 'Tracking and analysing website traffic and user behaviour', 'Building websites', 'Managing social media posts'], correct: 1, explanation: 'Google Analytics tracks website traffic, user behavior, conversions, and provides data-driven insights.' },
      { q: 'What is the primary goal of content marketing?', options: ['To directly sell products', 'To attract and engage audiences with valuable content', 'To increase website loading speed', 'To redesign the website'], correct: 1, explanation: 'Content marketing focuses on creating valuable, relevant content to attract, engage, and retain a clearly defined audience.' },
    ],
    certificateSkills: ['SEO & SEM', 'Content Marketing', 'Social Media Marketing', 'PPC & Google Ads'],
    certificateDescription: 'for successfully completing the SkillsXAI Digital Marketing Certification program and demonstrating proficiency in SEO, Content Marketing, Social Media Strategy, and PPC Advertising.',
    cheatSheets: [
      { title: 'Digital Marketing Cheat Sheet', file: 'digital-marketing-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
  {
    slug: 'ai-with-genai',
    title: 'AI with Generative AI Certification',
    shortTitle: 'AI with Gen AI',
    description: 'Learn artificial intelligence fundamentals, generative AI models, transformers, and real-world applications of ChatGPT, Claude, and Gemini.',
    icon: 'Brain',
    gradient: 'from-blue-500 to-cyan-400',
    accentColor: '#3b82f6',
    bgGradient: 'linear-gradient(135deg, #3b82f6 0%, #06b6d4 50%, #0ea5e9 100%)',
    videos: [
      { title: 'What is AI? Explained for Beginners', youtubeId: 'jPQmb2hZjAI', duration: '2:13' },
      { title: 'AI For Dummies — Everything You Need to Know', youtubeId: 'LbcUZUXM8Aw', duration: '8:00' },
    ],
    quizQuestions: [
      { q: 'What does "Generative AI" mean?', options: ['AI that classifies data', 'AI that creates new content like text, images, or code', 'AI that only analyses existing data', 'AI that runs on generators'], correct: 1, explanation: 'Generative AI refers to AI systems that can create new content — text, images, music, code — based on patterns learned from training data.' },
      { q: 'What is a Large Language Model (LLM)?', options: ['A very large dictionary', 'A neural network trained on massive text data to understand and generate language', 'A translation software', 'A programming language'], correct: 1, explanation: 'LLMs are neural networks trained on billions of words to understand context, generate text, and perform language tasks.' },
      { q: 'Which company created the GPT series of models?', options: ['Google', 'Meta', 'OpenAI', 'Apple'], correct: 2, explanation: 'OpenAI developed the GPT (Generative Pre-trained Transformer) series, including GPT-3.5 and GPT-4.' },
      { q: 'What is "prompt engineering"?', options: ['Building prompts for machinery', 'Crafting effective inputs/instructions for AI models to get desired outputs', 'Engineering physical displays', 'Creating notification systems'], correct: 1, explanation: 'Prompt engineering is the art and science of designing inputs that guide AI models to produce accurate and useful responses.' },
      { q: 'What is an AI "hallucination"?', options: ['When AI dreams', 'When AI generates plausible but factually incorrect information', 'A hardware error', 'An intentional AI feature'], correct: 1, explanation: 'AI hallucinations occur when models generate convincing but false or fabricated information not grounded in training data.' },
      { q: 'What is the "Transformer" architecture?', options: ['An electrical component', 'A neural network architecture using self-attention mechanisms', 'A data storage format', 'A type of robot'], correct: 1, explanation: 'Transformers are a neural network architecture that uses self-attention to process sequential data in parallel, powering models like GPT and BERT.' },
      { q: 'What is "fine-tuning" in AI?', options: ['Adjusting audio quality', 'Adapting a pre-trained model for a specific task with additional training', 'Fixing bugs in code', 'Tuning hardware frequency'], correct: 1, explanation: 'Fine-tuning takes a pre-trained model and trains it further on domain-specific data to specialize its capabilities.' },
      { q: 'Which of these can Generative AI create?', options: ['Only text', 'Only images', 'Only code', 'Text, images, code, music, and video'], correct: 3, explanation: 'Modern generative AI can produce text, images, code, music, video, 3D models, and more across different modalities.' },
      { q: 'What is "RAG" in the context of AI?', options: ['Random Access Generation', 'Retrieval-Augmented Generation', 'Rapid AI Growth', 'Real-time AI Gateway'], correct: 1, explanation: 'RAG (Retrieval-Augmented Generation) combines information retrieval with text generation, allowing AI to access external knowledge bases.' },
      { q: 'What is a "token" in the context of LLMs?', options: ['A digital coin', 'A piece of text (word or subword) that the model processes', 'An authentication key', 'A hardware chip'], correct: 1, explanation: 'Tokens are chunks of text — words, subwords, or characters — that LLMs use as their basic units of processing.' },
    ],
    certificateSkills: ['Artificial Intelligence', 'Generative AI Models', 'Prompt Engineering', 'AI Applications'],
    certificateDescription: 'for successfully completing the SkillsXAI AI with Generative AI Certification program and demonstrating proficiency in AI fundamentals, Generative AI models, Prompt Engineering, and real-world AI applications.',
    cheatSheets: [
      { title: 'AI & Gen AI Cheat Sheet', file: 'ai-genai-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
  {
    slug: 'ai-agents',
    title: 'AI Agents Certification',
    shortTitle: 'AI Agents',
    description: 'Build autonomous AI agents that perform tasks, make decisions, and automate workflows using n8n, LangChain, and no-code tools.',
    icon: 'Bot',
    gradient: 'from-purple-500 to-violet-500',
    accentColor: '#8b5cf6',
    bgGradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 50%, #6d28d9 100%)',
    videos: [
      { title: 'AI Agents Explained in Under 5 Minutes', youtubeId: 'FuRDMKqoArw', duration: '4:30' },
      { title: 'AI Agents Explained Like You\'re 5', youtubeId: 'wazHMMaiDEA', duration: '7:00' },
    ],
    quizQuestions: [
      { q: 'What is an AI Agent?', options: ['A chatbot only', 'An AI system that autonomously performs tasks and makes decisions', 'A physical robot', 'A search engine'], correct: 1, explanation: 'AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve specific goals.' },
      { q: 'What is "Tool Calling" in AI agents?', options: ['Using physical tools', 'When an AI invokes external APIs or functions to complete tasks', 'Calling customer support', 'A programming bug'], correct: 1, explanation: 'Tool calling allows AI agents to interact with external services — APIs, databases, email, etc. — to accomplish real-world tasks.' },
      { q: 'Which platform is popular for building no-code AI agents?', options: ['Photoshop', 'n8n', 'Microsoft Word', 'Windows Explorer'], correct: 1, explanation: 'n8n is a popular open-source workflow automation platform that enables building AI agents without coding.' },
      { q: 'What is a "workflow" in automation?', options: ['A physical path in a factory', 'A sequence of automated steps triggered by events or conditions', 'A type of exercise', 'A file management system'], correct: 1, explanation: 'A workflow is an automated sequence of tasks that execute in order, triggered by specific events or conditions.' },
      { q: 'What is multi-agent orchestration?', options: ['Playing music with AI', 'Coordinating multiple AI agents to work together on complex tasks', 'Running many computers', 'A networking protocol'], correct: 1, explanation: 'Multi-agent orchestration involves coordinating multiple specialized AI agents to collaborate on complex tasks, each handling different aspects.' },
      { q: 'What is a "trigger" in workflow automation?', options: ['A gun mechanism', 'An event that starts the execution of a workflow', 'A UI button', 'A database column'], correct: 1, explanation: 'A trigger is an event — like receiving an email, a form submission, or a schedule — that initiates the execution of an automated workflow.' },
      { q: 'What is the main advantage of AI agents over simple chatbots?', options: ['They are cheaper', 'They can take autonomous actions and interact with external systems', 'They have better UI', 'They work offline only'], correct: 1, explanation: 'AI agents go beyond Q&A — they can autonomously plan, use tools, access data, and execute multi-step tasks in the real world.' },
      { q: 'What does "memory" mean for an AI agent?', options: ['Computer RAM', 'The ability to recall previous interactions and maintain context', 'Storage space', 'A type of database'], correct: 1, explanation: 'Agent memory allows AI agents to remember past conversations, decisions, and context, enabling more coherent multi-turn interactions.' },
      { q: 'Which of these is NOT a common AI agent capability?', options: ['Sending emails automatically', 'Browsing the web', 'Physical object manipulation', 'Querying databases'], correct: 2, explanation: 'While AI agents excel at digital tasks (emails, web browsing, database queries), they cannot physically manipulate objects without robotic hardware.' },
      { q: 'What is a "sub-agent" in a multi-agent system?', options: ['A backup AI', 'A specialized agent delegated specific tasks by a main orchestrator agent', 'A smaller AI model', 'An AI in training'], correct: 1, explanation: 'Sub-agents are specialized agents that handle specific tasks delegated by a main orchestrator, enabling complex task decomposition.' },
    ],
    certificateSkills: ['AI Agents', 'Workflow Automation', 'Tool Calling & APIs', 'No-Code AI Development'],
    certificateDescription: 'for successfully completing the SkillsXAI AI Agents Certification program and demonstrating proficiency in building autonomous AI agents, workflow automation, tool calling, and no-code AI development.',
    cheatSheets: [
      { title: 'AI Agents Creation Cheat Sheet', file: 'ai-agents-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
  {
    slug: 'prompt-engineering',
    title: 'Prompt Engineering Certification',
    shortTitle: 'Prompt Engineering',
    description: 'Master the art of crafting effective prompts for ChatGPT, Claude, Gemini, and other AI models to get precise, high-quality outputs.',
    icon: 'MessageSquare',
    gradient: 'from-cyan-400 to-blue-500',
    accentColor: '#06b6d4',
    bgGradient: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 50%, #0284c7 100%)',
    videos: [
      { title: 'Learn Prompt Engineering in 7 Minutes — AWS', youtubeId: '-Hjw0_PMyfQ', duration: '7:00' },
      { title: 'How to Write Good AI Prompts', youtubeId: 'nN-czQqWuE4', duration: '8:30' },
    ],
    quizQuestions: [
      { q: 'What is "prompt engineering"?', options: ['Building physical prompts', 'Crafting effective instructions to guide AI models for desired outputs', 'A type of civil engineering', 'Programming hardware'], correct: 1, explanation: 'Prompt engineering is the discipline of designing and refining inputs to AI models to consistently produce high-quality, relevant outputs.' },
      { q: 'What is "zero-shot prompting"?', options: ['Using no AI at all', 'Asking AI to perform a task without providing any examples', 'A photography technique', 'Running AI without power'], correct: 1, explanation: 'Zero-shot prompting asks the model to perform a task based solely on the instruction, without any demonstration examples.' },
      { q: 'What is "few-shot prompting"?', options: ['Using very little text', 'Providing a few examples before the main task to guide the AI', 'Taking a few screenshots', 'A low-power AI mode'], correct: 1, explanation: 'Few-shot prompting includes 2-5 examples of the desired input-output format before the actual task, helping the AI understand the expected pattern.' },
      { q: 'What does "temperature" control in AI models?', options: ['The physical heat of the computer', 'The randomness/creativity of the AI\'s output', 'Processing speed', 'Memory usage'], correct: 1, explanation: 'Temperature controls output randomness: low values (0.0-0.3) produce focused, deterministic responses; high values (0.7-1.0) produce more creative, varied outputs.' },
      { q: 'What is "Chain-of-Thought" prompting?', options: ['Linking multiple AI models', 'Instructing AI to reason step-by-step before giving a final answer', 'Creating a chain of chatbots', 'A blockchain technique'], correct: 1, explanation: 'Chain-of-Thought prompting asks the model to show its reasoning process step-by-step, improving accuracy on complex problems.' },
      { q: 'What is a "system prompt"?', options: ['An OS notification', 'A hidden instruction that defines the AI\'s role, behaviour, and constraints', 'A system error message', 'A boot-up command'], correct: 1, explanation: 'System prompts are instructions set before the conversation that define the AI\'s persona, rules, and behaviour throughout the interaction.' },
      { q: 'Which element makes prompts MORE effective?', options: ['Being vague and open-ended', 'Adding clear context, role, and expected output format', 'Using all caps', 'Making the prompt as short as possible'], correct: 1, explanation: 'Effective prompts include clear context, a defined role, specific instructions, and the expected output format.' },
      { q: 'What is "hallucination" in AI responses?', options: ['Dreaming', 'When AI generates confident but factually incorrect information', 'A visual effect', 'An intended creative feature'], correct: 1, explanation: 'AI hallucinations occur when models produce plausible-sounding but incorrect or fabricated information, often with high confidence.' },
      { q: 'What is "RAG" and how does it relate to prompting?', options: ['A random number generator', 'Retrieval-Augmented Generation — adding retrieved documents to prompts for accuracy', 'A prompt formatting style', 'A type of AI model'], correct: 1, explanation: 'RAG enhances prompts by first retrieving relevant documents from a knowledge base, then including them as context for more accurate, grounded responses.' },
      { q: 'What is the best practice when a prompt doesn\'t give good results?', options: ['Give up and try a different AI', 'Iterate: refine the prompt with more context, examples, or constraints', 'Use a longer model name', 'Restart the computer'], correct: 1, explanation: 'Prompt iteration — refining wording, adding context, adjusting constraints, or providing examples — is the key to getting consistently good results.' },
    ],
    certificateSkills: ['Prompt Engineering', 'Zero-shot & Few-shot', 'Chain-of-Thought', 'AI Output Optimization'],
    certificateDescription: 'for successfully completing the SkillsXAI Prompt Engineering Certification program and demonstrating proficiency in crafting effective prompts, advanced prompting techniques, and AI output optimization.',
    cheatSheets: [
      { title: 'Prompt Engineering Cheat Sheet', file: 'prompt-engineering-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
  {
    slug: 'data-analytics',
    title: 'Data Analytics Certification',
    shortTitle: 'Data Analytics',
    description: 'Learn to analyse, visualise, and interpret data using Excel, SQL, Power BI, and Python to drive business decisions.',
    icon: 'BarChart3',
    gradient: 'from-emerald-400 to-teal-500',
    accentColor: '#10b981',
    bgGradient: 'linear-gradient(135deg, #10b981 0%, #14b8a6 50%, #0d9488 100%)',
    videos: [
      { title: 'What is Data Analytics? Explained in 8 Minutes — Simplilearn', youtubeId: 'gcF31GuwSEs', duration: '7:34' },
      { title: 'Data Analytics for Beginners — Google', youtubeId: 'GbL-42kv5LI', duration: '9:48' },
    ],
    quizQuestions: [
      { q: 'What is "data analytics"?', options: ['Storing data in databases', 'The process of examining data to find patterns, draw conclusions, and support decisions', 'Writing code', 'Building websites'], correct: 1, explanation: 'Data analytics is the science of examining raw data to find patterns, trends, and insights that inform business decisions.' },
      { q: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Question Logic', 'System Quality Level', 'Standard Query Listing'], correct: 0, explanation: 'SQL (Structured Query Language) is the standard language for managing and querying relational databases.' },
      { q: 'What is the difference between mean and median?', options: ['They are the same thing', 'Mean is the average; median is the middle value in a sorted dataset', 'Mean is always larger', 'Median is for text data only'], correct: 1, explanation: 'Mean is calculated by summing all values and dividing by count. Median is the middle value when data is sorted — it is less affected by outliers.' },
      { q: 'What is a KPI?', options: ['A programming language', 'Key Performance Indicator — a measurable value that shows progress toward goals', 'A data storage type', 'A network protocol'], correct: 1, explanation: 'KPIs are measurable values that demonstrate how effectively an organization is achieving key business objectives.' },
      { q: 'What is ETL?', options: ['A programming language', 'Extract, Transform, Load — the process of collecting and preparing data', 'An email protocol', 'A type of chart'], correct: 1, explanation: 'ETL is a data integration process: Extract data from sources, Transform it into a usable format, and Load it into a target system.' },
      { q: 'What is a data warehouse?', options: ['A physical building for servers', 'A centralised repository of integrated data from multiple sources for analysis', 'A backup drive', 'A cloud email service'], correct: 1, explanation: 'A data warehouse is a centralised system that stores structured, processed data from multiple sources, optimized for querying and analysis.' },
      { q: 'What is Power BI?', options: ['A battery brand', 'A business intelligence and data visualization tool by Microsoft', 'A power supply unit', 'A social media platform'], correct: 1, explanation: 'Power BI is Microsoft\'s business intelligence platform for creating interactive visualizations, reports, and dashboards from various data sources.' },
      { q: 'What does "correlation" mean in data analysis?', options: ['Causation', 'A statistical relationship between two variables', 'Data deletion', 'Random noise in data'], correct: 1, explanation: 'Correlation measures the statistical relationship between two variables — how they move together — but does not imply that one causes the other.' },
      { q: 'What is a "dashboard" in analytics?', options: ['A car component', 'A visual display of key metrics and data points for quick understanding', 'A keyboard shortcut', 'A coding IDE'], correct: 1, explanation: 'An analytics dashboard is a visual interface that displays key metrics, KPIs, and data visualizations for at-a-glance performance monitoring.' },
      { q: 'Which chart type is best for showing trends over time?', options: ['Pie chart', 'Line chart', 'Tree map', 'Scatter plot'], correct: 1, explanation: 'Line charts are ideal for displaying data trends over time, showing how values change across continuous intervals.' },
    ],
    certificateSkills: ['Data Analytics', 'SQL & Databases', 'Data Visualization', 'Business Intelligence'],
    certificateDescription: 'for successfully completing the SkillsXAI Data Analytics Certification program and demonstrating proficiency in data analysis, SQL, data visualization, and business intelligence tools.',
    cheatSheets: [
      { title: 'Data Analytics Cheat Sheet', file: 'data-analytics-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
  {
    slug: 'full-stack-ai',
    title: 'Full-Stack AI Development Certification',
    shortTitle: 'Full-Stack AI',
    description: 'Combine AI fundamentals, prompt engineering, agents, and data skills into one comprehensive full-stack AI certification.',
    icon: 'Layers',
    gradient: 'from-pink-500 to-rose-500',
    accentColor: '#ec4899',
    bgGradient: 'linear-gradient(135deg, #ec4899 0%, #f43f5e 50%, #e11d48 100%)',
    videos: [
      { title: 'What is AI? Explained for Beginners', youtubeId: 'jPQmb2hZjAI', duration: '2:13' },
      { title: 'Build a Full-Stack AI App in 10 Minutes', youtubeId: 'bVIKluY79Vw', duration: '8:57' },
    ],
    quizQuestions: [
      { q: 'What makes someone a "full-stack AI developer"?', options: ['Only knowing Python', 'Being able to build, integrate, and deploy AI applications end-to-end', 'Using one AI tool', 'Having a PhD in AI'], correct: 1, explanation: 'A full-stack AI developer can work across the entire AI application stack — from model selection and prompting to API integration, agent building, and deployment.' },
      { q: 'What is an API key?', options: ['A physical key', 'A secret credential that authenticates your application to use an AI service', 'A keyboard shortcut', 'A file extension'], correct: 1, explanation: 'API keys are secret credentials that identify your application and grant access to AI services, and must be kept secure.' },
      { q: 'What is the AI "stack"?', options: ['A pile of papers', 'The combination of technologies used to build AI applications (models, APIs, frameworks, deployment)', 'A data structure', 'A type of neural network'], correct: 1, explanation: 'The AI stack refers to the layers of technology — foundation models, APIs, frameworks, orchestration tools, and deployment platforms — used together.' },
      { q: 'Why is version control important for AI projects?', options: ['It is not important', 'To track changes, collaborate, and rollback if something breaks', 'Only for large teams', 'To make code run faster'], correct: 1, explanation: 'Version control (Git) tracks all code changes, enables team collaboration, and allows safe rollback if AI models or prompts produce unexpected results.' },
      { q: 'What is an "embedding" in AI?', options: ['Inserting text into a document', 'A numerical vector representation of data that captures semantic meaning', 'A CSS property', 'An HTML element'], correct: 1, explanation: 'Embeddings convert text, images, or other data into numerical vectors that capture semantic meaning, enabling similarity search and retrieval.' },
      { q: 'What is "streaming" in the context of AI APIs?', options: ['Video streaming', 'Receiving AI output progressively token-by-token instead of waiting for the full response', 'Data pipelines', 'Audio playback'], correct: 1, explanation: 'Streaming delivers AI responses incrementally as they are generated, improving perceived speed and user experience.' },
      { q: 'What is a vector database used for?', options: ['Storing videos', 'Storing and searching high-dimensional embedding vectors for similarity matching', 'Managing user accounts', 'Hosting websites'], correct: 1, explanation: 'Vector databases store embedding vectors and enable fast similarity searches, powering RAG systems, recommendation engines, and semantic search.' },
      { q: 'What is "model orchestration"?', options: ['Playing music', 'Coordinating multiple AI models and tools to work together on complex tasks', 'Training one model', 'Deleting models'], correct: 1, explanation: 'Model orchestration involves routing requests to appropriate models, managing fallbacks, and coordinating multiple AI components in a pipeline.' },
      { q: 'Which is NOT a common AI deployment platform?', options: ['Vercel', 'AWS Lambda', 'Microsoft Word', 'Google Cloud Run'], correct: 2, explanation: 'Vercel, AWS Lambda, and Google Cloud Run are deployment platforms. Microsoft Word is a document editor, not a deployment platform.' },
      { q: 'What is "responsible AI"?', options: ['AI that responds quickly', 'Developing AI systems that are fair, transparent, accountable, and minimize harm', 'AI that saves money', 'AI that works offline'], correct: 1, explanation: 'Responsible AI encompasses practices ensuring AI systems are ethical, fair, transparent, safe, and accountable in their design and deployment.' },
    ],
    certificateSkills: ['Full-Stack AI', 'API Integration', 'AI Agents', 'AI Deployment'],
    certificateDescription: 'for successfully completing the SkillsXAI Full-Stack AI Development Certification program and demonstrating comprehensive proficiency across AI fundamentals, prompt engineering, agent development, and AI application deployment.',
    cheatSheets: [
      { title: 'Full-Stack AI Cheat Sheet', file: 'ai-genai-cheatsheet.html' },
      { title: 'AI Agents Creation Cheat Sheet', file: 'ai-agents-cheatsheet.html' },
      { title: 'NVIDIA Models API Shortcuts', file: 'nvidia-api-shortcuts.html' },
      { title: 'AI Website Prompts Collection', file: 'ai-website-prompts.html' },
    ],
  },
]

export function getCourseBySlug(slug: string): CourseConfig | undefined {
  return courses.find((c) => c.slug === slug)
}
